server:
  servlet:
    context-path: /spring
  port: 8000
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.1.1:1521:oracledb
    username: odb
    password: odb
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    show-sql: true
logging:
  level:
    th.in.lordgift.SpringBoot2Tutorial.*: debug


#ojdbc7.jar
